name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          branch: main
          appdir: front
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "omikron-front"
          heroku_email: "lucas.descause@gmail.com"
          usedocker: true
          docker_build_args: |
            NODE_ENV
            VITE_BASE_BACKEND_URL
        env:
          NODE_ENV: production
          VITE_BASE_BACKEND_URL: ${{vars.VITE_BASE_BACKEND_URL}}
  back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          branch: main
          appdir: back
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "omikron-back"
          heroku_email: "lucas.descause@gmail.com"
          usedocker: true
          docker_build_args: NODE_ENV
        env:
          HD_NODE_ENV: production
          HD_DB_USER: ${{vars.DB_USER}}
          HD_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          HD_DB_HOST: ${{vars.DB_HOST}}
          HD_DB_DB: ${{vars.DB_DB}}
          HD_DB_PORT: ${{vars.DB_PORT}}
          HD_DB_SSL: ${{vars.DB_SSL}}
          HD_MQ_CONNNEXTION_STRING: ${{secrets.MQ_CONNNEXTION_STRING}}
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
