name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          branch: main
          appdir: front
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "omikron-front"
          heroku_email: "lucas.descause@gmail.com"
          usedocker: true
          docker_build_args: |
            NODE_ENV
            SECRET_KEY
        env:
          NODE_ENV: production
          VITE_BASE_BACKEND_URL: http://localhost:3000
