name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          branch: main
          appdir: front
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "omikron-front"
          heroku_email: "lucas.descause@gmail.com"
          usedocker: true
  back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          branch: main
          appdir: back
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "omikron-back"
          heroku_email: "lucas.descause@gmail.com"
          usedocker: true
