name: Run Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
        working-directory: ./back
      - name: Run tests
        run: npm run test:cov
        working-directory: ./back
